version: 2.1
jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Build the Docker image
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t your-image-name:${CIRCLE_SHA1} .
            docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
            docker tag your-image-name:${CIRCLE_SHA1} gcr.io/your-gcp-project/your-image-name:${CIRCLE_SHA1}
            docker push gcr.io/your-gcp-project/your-image-name:${CIRCLE_SHA1}

  deploy_to_gke:
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout

      # Configure Google Cloud SDK
      - run:
          name: Configure Google Cloud SDK
          command: |
            echo $GCP_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcp-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-service-key.json
            gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone --project your-gcp-project

      # Deploy to GKE
      - run:
          name: Deploy to GKE
          command: |
            kubectl set image deployment/your-deployment-name your-container-name=gcr.io/your-gcp-project/your-image-name:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push
      - deploy_to_gke:
          requires:
            - build_and_push
